// products
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS" ;
export const FETCH_PRODUCTS_ERROR   = "FETCH_PRODUCTS_ERROR";

export const FETCH_FILTERS_PENDING  = "FETCH_FILTERS_PENDING";
export const FETCH_FILTERS_SUCCESS  = "FETCH_FILTERS_SUCCESS";
export const FETCH_FILTERS_ERROR    = "FETCH_FILTERS_ERROR";

export const SELECT_FILTER          = "SELECT_FILTER";
